# backend/app/brand_products.py

BRAND_PRODUCTS = [
    {
        "id": "lw-101",
        "name": "Soft Matte Foundation",
        "shade_name": "Porcelain 100",
        "hex": "#F4D7C8",
        "tone": "light",
        "undertone": "cool",
        "category": "foundation",
        "coverage": "medium",
    },
    {
        "id": "lw-102",
        "name": "Soft Matte Foundation",
        "shade_name": "Warm Ivory 130",
        "hex": "#F3C9AA",
        "tone": "light",
        "undertone": "warm",
        "category": "foundation",
        "coverage": "medium",
    },
    {
        "id": "lw-103",
        "name": "Soft Matte Foundation",
        "shade_name": "Neutral Beige 180",
        "hex": "#E3B088",
        "tone": "light-medium",
        "undertone": "neutral",
        "category": "foundation",
        "coverage": "medium",
    },
    {
        "id": "lw-104",
        "name": "Soft Matte Foundation",
        "shade_name": "Warm Sand 220",
        "hex": "#D2A676",
        "tone": "medium",
        "undertone": "warm",
        "category": "foundation",
        "coverage": "medium",
    },
    {
        "id": "lw-105",
        "name": "Soft Matte Foundation",
        "shade_name": "Olive Tan 260",
        "hex": "#BF8C5F",
        "tone": "medium",
        "undertone": "olive",
        "category": "foundation",
        "coverage": "medium",
    },
    {
        "id": "lw-106",
        "name": "Soft Matte Foundation",
        "shade_name": "Caramel 310",
        "hex": "#A3633C",
        "tone": "tan",
        "undertone": "warm",
        "category": "foundation",
        "coverage": "full",
    },
    {
        "id": "lw-107",
        "name": "Soft Matte Foundation",
        "shade_name": "Neutral Mocha 340",
        "hex": "#8C5333",
        "tone": "tan",
        "undertone": "neutral",
        "category": "foundation",
        "coverage": "full",
    },
    {
        "id": "lw-108",
        "name": "Soft Matte Foundation",
        "shade_name": "Deep Cocoa 410",
        "hex": "#5A3521",
        "tone": "deep",
        "undertone": "warm",
        "category": "foundation",
        "coverage": "full",
    },
    {
        "id": "lw-109",
        "name": "Soft Matte Foundation",
        "shade_name": "Cool Espresso 430",
        "hex": "#3D2518",
        "tone": "deep",
        "undertone": "cool",
        "category": "foundation",
        "coverage": "full",
    },
]
